### ISSUE TITLE
Could we make this component a part of HACS?

### ISSUE THREAD

**Issue by ghost** [wijnandtop/home_assistant_gardena#12]
All doc here: https://hacs.xyz/docs/developer/start

I tried in this repo but did not manage: https://github.com/berg2gadm/gardena

thanks!

**Comment by kayloehmann** [comment]
I created my own copy, HACS ready.
https://github.com/kayloehmann/homeassistant_gardena

**Comment by Jpsy** [comment]
Why didn't you create a pull request or become a contributor in THIS repo? Unnecessary forks will create unnecessary work if both lines evolve on.

**Comment by kayloehmann** [comment]
> Why didn't you create a pull request or become a contributor in THIS repo? Unnecessary forks will create unnecessary work if both lines evolve on.

Nobody seems to work on this anymore. Thats why.

**Comment by Jpsy** [comment]
That's why you could ask to become a contributor.

**Comment by kayloehmann** [comment]
> That's why you could ask to become a contributor.

I dont get your point: A fork is a copy of a repository. Forking a repository allows you to freely experiment with changes without affecting the original project.

Thats also something i wanted to do.

**Comment by wijnandtop** [comment]
Thanks for the great work in making it work again, do all features work? 
I'm open for merge-requests or adding someone as a contributor. This way we can keep one implementation to avoid confusion for potential users.

Unfortunately I didn't have time pasts months to work on the project.  But it is still on my todo also since I own most of the gardena devices. Some devices will be added in the python library would be great if we can easily implement them in the HASS plugin as well.

The project will benefit if we share the responsibility of maintenance!

**Comment by TheFitzZZ** [comment]
Having just bought one of the sets with the bridge, one sensor and the irrigation controller I also have quite the interest in having this in HA. I'll try to wrap my head around stuff and will probably start with a PR to add HACS support in here as I'm also not a fan of more forks, especially since you're still "active" :-)

**Comment by northpower25** [comment]
If you want a fast solution to bring the Gardena Set to work with HA you can use the homekit integration with less limitation (eg no humity temperature sensor). Please let us know about your PR that we can support this. If yourself will engage in this here you find the Gardena API Documentation https://developer.1689.cloud/apis/GARDENA+smart+system+API

**Comment by wijnandtop** [comment]
The component is now HACS compatible and can be installed by adding this repo to HACS.
